core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    
    # Ana uygulamalar
    path('', include('webui.urls')),
    
    
    # Forum URL'leri - Doğru yolu kullanın
    path('forum/', include('forum.urls')),
    
    # Medya dosyaları için URL yapılandırması
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Debug True ise statik dosyaları da servis et
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    # Ana forum sayfası
    path('', views.forum_main, name='forum_main'),
    
    # Tüm konuları listele
    path('tum-konular/', views.tum_konulari_goster, name='tum_konular'),
    
    # Kategori ve konu işlemleri
    path('kategori/<slug:kategori_slug>/', views.kategori_detay, name='kategori_detay'),
    path('kategori/<slug:kategori_slug>/konu/<slug:konu_slug>/', views.konu_detay, name='konu_detay'),
    path('yeni-konu/', views.yeni_konu, name='yeni_konu'),
    path('yeni-konu/<slug:kategori_slug>/', views.yeni_konu, name='yeni_konu_kategori'),
    path('konu-duzenle/<int:konu_id>/', views.konu_duzenle, name='konu_duzenle'),
    path('konu-sil/<int:konu_id>/', views.konu_sil, name='konu_sil'),
    
    # Kullanıcı konuları
    path('konularim/', views.kullanici_konular, name='kullanici_konular'),
    
    # Normal kullanıcılar için kategori listesi
    path('kategoriler/', views.kullanici_forum_kategori_listele, name='kullanici_forum_kategori_listele'),
    
    # Yorum işlemleri
    path('yorum-duzenle/<int:yorum_id>/', views.yorum_duzenle, name='yorum_duzenle'),
    path('yorum-sil/<int:yorum_id>/', views.yorum_sil, name='yorum_sil'),
    
    # Beğeni işlemleri
    path('begeni-ekle/', views.begeni_ekle, name='begeni_ekle'),
    
    # Arama
    path('arama/', views.forum_arama, name='forum_arama'),
    
    # Yönetim paneli URL'leri - Kategoriler
    path('yonetim/kategoriler/', views.forum_kategori_listele, name='forum_kategori_listele'),
    path('yonetim/kategori/ekle/', views.forum_kategori_ekle, name='forum_kategori_ekle'),
    path('yonetim/kategori/duzenle/<int:kategori_id>/', views.forum_kategori_duzenle, name='forum_kategori_duzenle'),
    path('yonetim/kategori/sil/<int:kategori_id>/', views.forum_kategori_sil, name='forum_kategori_sil'),
    
    # Yönetim paneli URL'leri - Konular
    path('yonetim/konular/', views.forum_konu_listele, name='forum_konu_listele'),
    path('yonetim/konu/ekle/', views.forum_konu_ekle, name='forum_konu_ekle'),
    path('yonetim/konu/duzenle/<int:konu_id>/', views.forum_konu_duzenle, name='forum_konu_duzenle'),
    path('yonetim/konu/sil/<int:konu_id>/', views.forum_konu_sil, name='forum_konu_sil'),
    
    # Yönetim paneli URL'leri - Yorumlar
    path('yonetim/yorumlar/', views.forum_yorum_listele, name='forum_yorum_listele'),
    path('yonetim/yorum/duzenle/<int:yorum_id>/', views.forum_yorum_duzenle, name='forum_yorum_duzenle'),
    path('yonetim/yorum/sil/<int:yorum_id>/', views.forum_yorum_sil, name='forum_yorum_sil'),
    
    # Konu Onay Sistemi URL'leri
    path('yonetim/onay-bekleyen-konular/', views.forum_konu_onay_listesi, name='forum_konu_onay_listesi'),
    path('yonetim/konu-onayla/<int:konu_id>/', views.forum_konu_onayla, name='forum_konu_onayla'),
    path('yonetim/konu-reddet/<int:konu_id>/', views.forum_konu_reddet, name='forum_konu_reddet'),
]

core/templates/includes/about.html
{% load static %}
<section class="about-one section-space" id="about">
  <div class="about-one__bg"></div>
  <div class="container">
    <div class="row gutter-y-50">
      <div class="col-lg-6">
        <div class="about-one__content">
          <div class="sec-title wow fadeInUp" data-wow-duration="1500ms">
            <h6 class="sec-title__tagline">HAKKIMIZDA</h6>
            <h3 class="sec-title__title">Kendine<span class="sec-title__title"> İyi</span> <span class="sec-title__title">Bak</span></h3>
          </div>
          <div class="about-one__text wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="100ms">
            <p>Kendine İyi Bak programı siz ve demans hastası yakınınız için hazırlanmıştır. İçeriğinde sizin ve yakınınızın bu süreci en iyi şekilde devam ettirebilmeniz için hastalık ve sürece yönelik bilgiler, aktiviteler yer almaktadır. Amacımız demans hastalığına yönelik eğitim ve danışmanlık hizmeti almanız ve diğer bakım verenlerle etkileşim, bilgi, deneyim paylaşımı sağlayabilmenizdir.</p>
          </div>
          <ul class="about-one__list list-unstyled wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="200ms">
            <li>
              <span class="about-one__list__icon"><i class="icon-confirmation"></i></span>
              <div class="about-one__list__content">
                <h4 class="about-one__list__title">Eğitimler ve Aktiviteler</h4>
                <p class="about-one__list__text">8 hafta boyunca her hafta farklı bir konu olmak üzere eğitim verilecektir. Her eğitim konusu ve etkinlik haftalık planlanmıştır.</p>
              </div>
            </li>
            <li>
              <span class="about-one__list__icon"><i class="icon-confirmation"></i></span>
              <div class="about-one__list__content">
                <h4 class="about-one__list__title">Danışmanlık</h4>
                <p class="about-one__list__text">10 haftalık süreç boyunca çalışmanın yürütücülerinden danışmanlık hizmeti alabilirsiniz. Bu hizmetten yararlanmak için programda yer alan bölümden randevu oluşturmanız yeterlidir. Canlı görüşme haricinde istediğiniz zaman mesaj kutusunu kullanarak eğitimcilere soru ve paylaşımlarınızı iletebilirsiniz.</p>
              </div>
            </li>
            <li>
              <span class="about-one__list__icon"><i class="icon-confirmation"></i></span>
              <div class="about-one__list__content">
                <h4 class="about-one__list__title">Forum</h4>
                <p class="about-one__list__text">Zaman sınırlaması olmaksızın diğer bakım verenlerle etkileşim, bilgi, deneyim paylaşımda bulunabileceğiniz çevrimiçi forum özelliği bulunmaktadır.</p>
              </div>
            </li>
          </ul>
          <div class="about-one__button wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="300ms">
            {% if user.is_authenticated %}
              <a href="{% url 'courses' %}" class="eduhive-btn">
            {% else %}
              <a href="{% url 'access_denied' %}" class="eduhive-btn">
            {% endif %}
              <span>Eğitimleri İncele</span>
              <span class="eduhive-btn__icon"><span class="eduhive-btn__icon__inner"><i class="icon-right-arrow"></i></span></span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="about-one__image wow fadeInRight" data-wow-duration="1500ms">
          <img style="width: 700px;" src="{% static 'assets/images/about/kendine_iyi_bak_logo.png' %}" alt="Demans Hasta Bakıcı Eğitimi" />
          <div class="about-one__image__shape"></div>
          <div class="about-one__image__years">
            <div class="about-one__image__years__inner">
              <!-- <span class="about-one__image__years__number">10</span>
              Yıllık<br />Deneyim -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

core/templates/includes/categories.html
{% load static %}
<section class="course-category section-space">
  <div class="container">
    <div class="sec-title sec-title--center wow fadeInUp" data-wow-duration="1500ms">
      <h6 class="sec-title__tagline">Eğitim Kategorilerimiz</h6>
      <h3 class="sec-title__title">Demans Hasta Bakıcı <span class="sec-title__title__text">Eğitim</span> <span class="sec-title__title__shape">Programları</span></h3>
    </div>
    <div class="row gutter-y-30">
      <!-- Temel Bakım -->
      <div class="col-xl-3 col-lg-4 col-sm-6">
        <div class="course-category__card wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="000ms">
          <div class="course-category__card__inner">
            <div class="course-category__card__bg" style="background-image: url({% static 'assets/images/course-category/temel-bakim.jpg' %});"></div>
          </div>
          <div class="course-category__card__content">
            <div class="course-category__card__icon-box">
              <span class="course-category__card__icon"><i class="icon-health"></i></span>
            </div>
            <h4 class="course-category__card__title">Temel Bakım Eğitimi</h4>
          </div>
        </div>
      </div>

      <!-- İletişim -->
      <div class="col-xl-3 col-lg-4 col-sm-6">
        <div class="course-category__card wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="100ms">
          <div class="course-category__card__inner">
            <div class="course-category__card__bg" style="background-image: url({% static 'assets/images/course-category/iletisim.jpg' %});"></div>
          </div>
          <div class="course-category__card__content">
            <div class="course-category__card__icon-box">
              <span class="course-category__card__icon"><i class="icon-chat"></i></span>
            </div>
            <h4 class="course-category__card__title">İletişim Teknikleri</h4>
          </div>
        </div>
      </div>

      <!-- Günlük Yaşam -->
      <div class="col-xl-3 col-lg-4 col-sm-6">
        <div class="course-category__card wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="200ms">
          <div class="course-category__card__inner">
            <div class="course-category__card__bg" style="background-image: url({% static 'assets/images/course-category/gunluk-yasam.jpg' %});"></div>
          </div>
          <div class="course-category__card__content">
            <div class="course-category__card__icon-box">
              <span class="course-category__card__icon"><i class="icon-home"></i></span>
            </div>
            <h4 class="course-category__card__title">Günlük Yaşam Desteği</h4>
          </div>
        </div>
      </div>

      <!-- Beslenme -->
      <div class="col-xl-3 col-lg-4 col-sm-6">
        <div class="course-category__card wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="300ms">
          <div class="course-category__card__inner">
            <div class="course-category__card__bg" style="background-image: url({% static 'assets/images/course-category/beslenme.jpg' %});"></div>
          </div>
          <div class="course-category__card__content">
            <div class="course-category__card__icon-box">
              <span class="course-category__card__icon"><i class="icon-food"></i></span>
            </div>
            <h4 class="course-category__card__title">Beslenme ve Diyet</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

core/templates/includes/css.html
{% load static %}
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/kendine_iyi_bak_logo.png' %}" />
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/kendine_iyi_bak_logo.png' %}" />
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/kendine_iyi_bak_logo.png' %}" />
<link rel="manifest" href="{% static 'assets/manifest.json' %}" />
<meta name="description" content="Eduhive is a very modern and versatile education & online courses HTML Template. It is specially designed for LMS, online courses, education, learning management, e-learning, online training, zoom classes, and all other education related websites and businesses." />

<!-- fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=Cormorant:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet" />

<link rel="stylesheet" href="{% static 'assets/vendors/bootstrap/css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/bootstrap-select/bootstrap-select.min.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/animate/animate.min.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/fontawesome/css/all.min.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/jquery-ui/jquery-ui.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/jarallax/jarallax.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/nouislider/nouislider.min.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/nouislider/nouislider.pips.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/tiny-slider/tiny-slider.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/eduhive-icons/style.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/css/owl.carousel.min.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/css/owl.theme.default.min.css' %}" />

<!-- template styles -->
<link rel="stylesheet" href="{% static 'assets/css/eduhive.css' %}" />

core/templates/includes/faq.html
{% load static %}
<section class="faq-one section-space">
  <div class="container">
    <div class="row gutter-y-50">
      <div class="col-lg-6">
        <div class="faq-one__content">
          <div class="sec-title wow fadeInUp" data-wow-duration="1500ms">
            <h6 class="sec-title__tagline">SIK SORULAN SORULAR</h6>
            <h3 class="sec-title__title">“Kendine İyi Bak” <span class="sec-title__title">Programı</span> <span class="sec-title__title__shape">Hakkında</span></h3>
          </div>
          <div class="faq-one__accordion">
            <div class="eduhive-accordion" data-grp-name="eduhive-accordion">
              <div class="accordion active wow fadeInUp" data-wow-duration="1500ms">
                <div class="accordion-title">
                  <h4>Program ne kadar sürüyor?</h4>
                  <span class="accordion-title__icon"><i class="icon-double-arrow"></i></span>
                </div>
                <div class="accordion-content">
                  <div class="inner">
                    <p>10 hafta sürecektir. 8 hafta boyunca her hafta farklı bir konu olmak üzere eğitim verilecektir. Her eğitim konusu ve etkinlik haftalık planlanmıştır. Paylaşıma haftası geldiğinde açılacaktır.</p>
                  </div>
                </div>
              </div>

              <!--    <div class="accordion wow fadeInUp" data-wow-duration="1500ms">
                <div class="accordion-title">
                  <h4>Eğitimler Online mı Veriliyor?</h4>
                  <span class="accordion-title__icon"><i class="icon-double-arrow"></i></span>
                </div>
                <div class="accordion-content">
                  <div class="inner">
                    <p>Evet, eğitimlerimiz tamamen online olarak verilmektedir. Teorik dersler canlı ve kayıtlı videolarla, pratik uygulamalar ise interaktif çalışmalarla desteklenmektedir.</p>
                  </div>
                </div>
              </div>    -->

              <div class="accordion wow fadeInUp" data-wow-duration="1500ms">
                <div class="accordion-title">
                  <h4>Program sonundan ne kazanacağım?</h4>
                  <span class="accordion-title__icon"><i class="icon-double-arrow"></i></span>
                </div>
                <div class="accordion-content">
                  <div class="inner">
                    <p>Programa katılımın sonunda sizlerin bakım sürecinde hissetmiş olduğunuz yükünüzün azalması, bakım vermeye kendinize hazır hissetmeniz, demanslı yakınınızın bilişsel sağlık düzeyinin iyileşmesi ve davranışsal semptomlarının hafifletilmesi hedeflenmektedir.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 wow fadeInRight" data-wow-duration="1500ms">
        <div class="faq-one__image">
          <div class="faq-one__image__one">
            <div class="faq-one__image__one__inner">
              <img src="{% static 'assets/images/faq/Resim1.jpg' %}" alt="Demans Eğitimi" />
            </div>
          </div>
          <div class="faq-one__image__two">
            <!-- <img src="{% static 'assets/images/gallery/10.png' %}" alt="Demans Bakımı" /> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

core/templates/includes/footer.html
{% load static %}

<footer class="main-footer section-space-top">
  <div class="container">
    <!-- /.main-footer__top -->
    <div class="row gutter-y-40">
      <div class="col-xl-4 col-lg-4 wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="00ms">
        <div class="footer-widget footer-widget--about">
          <h2 class="footer-widget__title">Hakkımızda</h2><!-- /.footer-widget__title -->
          <p class="footer-widget__about-text">Demanslı yakınınıza ve kendinize daha iyi bakmanız için gerekli bilgi ve becerileri edinin.</p>
          <!-- /.footer-widget__about-text -->
        </div>
        <!-- /.footer-widget -->
      </div>
      <!-- /.col-xl-4 col-lg-4 -->
      <div class="col-xl-4 col-md-6 col-sm-12 wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="100ms">
        <div class="footer-widget footer-widget--links">
          <h2 class="footer-widget__title">Hızlı Erişim</h2><!-- /.footer-widget__title -->
          <ul class="list-unstyled footer-widget__links">
            <li>
              <a href="{% url 'index' %}">
                <span class="footer-widget__links__icon"><i class="icon-double-arrow"></i></span>
                Ana Sayfa
              </a>
            </li>
            <li>
              <a href="{% url 'index' %}#about">
                <span class="footer-widget__links__icon"><i class="icon-double-arrow"></i></span>
                Hakkımızda
              </a>
            </li>
            <li>
              {% if user.is_authenticated %}
                <a href="{% url 'courses' %}">
                  <span class="footer-widget__links__icon"><i class="icon-double-arrow"></i></span>
                  Eğitimler
                </a>
              {% else %}
                <a href="{% url 'access_denied' %}">
                  <span class="footer-widget__links__icon"><i class="icon-double-arrow"></i></span>
                  Eğitimler
                </a>
              {% endif %}
            </li>
            <li>
              {% if user.is_authenticated %}
                <a href="{% url 'profil' %}">
                  <span class="footer-widget__links__icon"><i class="icon-double-arrow"></i></span>
                  Profilim
                </a>
              {% else %}
                <a href="{% url 'giris' %}">
                  <span class="footer-widget__links__icon"><i class="icon-double-arrow"></i></span>
                  Giriş Yap
                </a>
              {% endif %}
            </li>
            <li>
              {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">
                  <span class="footer-widget__links__icon"><i class="icon-double-arrow"></i></span>
                  Çıkış Yap
                </a>
              {% else %}
                <a href="{% url 'kayit' %}">
                  <span class="footer-widget__links__icon"><i class="icon-double-arrow"></i></span>
                  Kayıt Ol
                </a>
              {% endif %}
            </li>
          </ul>
          <!-- /.list-unstyled footer-widget__links -->
        </div>
        <!-- /.footer-widget -->
      </div>
      <!-- /.col-xl-4 col-md-6 col-sm-12 -->
      <div class="col-xl-4 col-md-6 col-sm-12 wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="200ms">
        <div class="footer-widget footer-widget--contact">
          <h2 class="footer-widget__title">İletişim Bilgileri</h2><!-- /.footer-widget__title -->
          <ul class="footer-widget__info">
            <li style="display: none;">
              <span class="footer-widget__info__icon"><i class="icon-location"></i></span>
              <a href="https://www.google.com/maps">İstanbul, Türkiye</a>
            </li>
            <li>
              <span class="footer-widget__info__icon"><i class="icon-email"></i></span>
              <a href="mailto:aysunmutlu25@gmail.com">aysunmutlu25@gmail.com</a>
            </li>
            <li>
              <span class="footer-widget__info__icon"><i class="icon-telephone"></i></span>
              <a href="tel:+905367655107">+90 536 765 51 07</a>
            </li>
          </ul>
          <!-- /.footer-widget__info -->
        </div>
        <!-- /.footer-widget -->
      </div>
      <!-- /.col-xl-4 col-md-6 col-sm-12 -->
    </div>
    <!-- /.row gutter-y-40 -->
  </div>
  <!-- /.container -->
  <div class="main-footer__bottom">
    <div class="container">
      <div class="main-footer__bottom__inner d-flex justify-content-center">
        <!--     <p class="main-footer__copyright text-center w-100">
          &copy; Copyright <span class="dynamic-year"></span> Kendine İyi Bak. Tüm Hakları Saklıdır.
        </p>     -->
      </div>
      <!-- /.main-footer__inner -->
    </div>
    <!-- /.container -->
  </div>
</footer>

core/templates/includes/header.html
{% load static %}
<header class="main-header sticky-header sticky-header--normal">
  <div class="container-fluid">
    <div class="main-header__inner">
      <div class="main-header__logo logo-retina">
        <a href="{% url 'index' %}"><img src="{% static 'assets/images/kendine_iyi_bak_logo.png' %}" alt="Kendine İyi Bak" width="100" class="logo-dark" /></a>
      </div>
      <!-- /.main-header__logo -->
      <div class="main-header__right">
        <nav class="main-header__nav main-menu">
          <ul class="main-menu__list">
            <li>
              <a href="{% url 'index' %}">Ana Sayfa</a>
            </li>
            <li>
              <a href="{% url 'index' %}#about">Hakkımızda</a>
            </li>
            <li>
              {% if user.is_authenticated %}
                <a href="{% url 'courses' %}">Eğitimler</a>
              {% else %}
                <a href="{% url 'access_denied' %}">Eğitimler</a>
              {% endif %}
            </li>
            <li>
              <a href="{% url 'forum:forum_main' %}">Forum</a>
            </li>

            {% if user.is_staff or user.is_superuser %}
              <li>
                <a href="{% url 'yonetim_paneli' %}">Yönetim Paneli</a>
              </li>
            {% endif %}
          </ul>
        </nav>
        <!-- /.main-header__nav -->
        <div class="mobile-nav__btn mobile-nav__toggler">
          <span></span>
          <span></span>
          <span></span>
        </div>
        <!-- /.mobile-nav__toggler -->

        {% if user.is_authenticated %}
          <div class="user-menu">
            {% if request.user.okunmayan_mesaj_sayisi > 0 %}
              <div class="notification-dot"></div>
            {% endif %}
            <a href="{% url 'profil' %}" class="user-menu__link">
              <i class="fa fa-user-circle"></i>
              <span>{{ user.fullname|default:user.username }}</span>
            </a>
            <div class="user-menu__dropdown">
              <a href="{% url 'profil' %}">Profilim</a>
              <a href="{% url 'mesajlar' %}">
                Mesajlar{% if request.user.okunmayan_mesaj_sayisi > 0 %}
                  <span class="badge bg-danger rounded-pill">{{ request.user.okunmayan_mesaj_sayisi }}</span>
                {% endif %}
              </a>
              <a href="{% url 'gorusme_listesi' %}">Görüntülü Görüşmeler</a>
              {% if user.is_staff or user.is_superuser %}
                <a href="{% url 'yonetim_paneli' %}">Yönetim Paneli</a>
              {% endif %}
              <a href="{% url 'logout' %}">Çıkış Yap</a>
            </div>
          </div>
        {% else %}
          <div class="auth-buttons" style="display: flex; gap: 10px;">
            <a href="{% url 'giris' %}" class="main-header__btn eduhive-btn eduhive-btn--border">
              <span>Giriş Yap</span>
              <span class="eduhive-btn__icon"><span class="eduhive-btn__icon__inner"><i class="icon-right-arrow"></i></span></span>
            </a>
            <a href="{% url 'kayit' %}" class="main-header__btn eduhive-btn">
              <span>Kayıt Ol</span>
              <span class="eduhive-btn__icon"><span class="eduhive-btn__icon__inner"><i class="icon-right-arrow"></i></span></span>
            </a>
          </div>
        {% endif %}
      </div>
      <!-- /.main-header__right -->
    </div>
    <!-- /.main-header__inner -->
  </div>
  <!-- /.container-fluid -->
</header>

<style>
  .user-menu {
    position: relative;
    margin-left: 15px;
  }
  
  .user-menu__link {
    display: flex;
    align-items: center;
    color: #333;
    text-decoration: none;
    padding: 8px 15px;
    border-radius: 30px;
    background-color: #f0f0f0;
    transition: all 0.3s ease;
  }
  
  .user-menu__link:hover {
    background-color: #e0e0e0;
  }
  
  .user-menu__link i {
    font-size: 18px;
    margin-right: 8px;
    color: #6610f2;
  }
  
  .user-menu__dropdown {
    position: absolute;
    top: 100%;
    right: 0;
    width: 180px;
    background-color: #fff;
    border-radius: 8px;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
    padding: 10px 0;
    margin-top: 10px;
    opacity: 0;
    visibility: hidden;
    transform: translateY(10px);
    transition: all 0.3s ease;
    z-index: 100;
  }
  
  .user-menu:hover .user-menu__dropdown {
    opacity: 1;
    visibility: visible;
    transform: translateY(0);
  }
  
  .user-menu__dropdown a {
    display: block;
    padding: 10px 20px;
    color: #333;
    text-decoration: none;
    transition: all 0.3s ease;
  }
  
  .user-menu__dropdown a:hover {
    background-color: #f5f5f5;
    color: #6610f2;
  }
  
  /* Auth Buttons */
  .auth-buttons {
    display: flex;
    gap: 5px;
  }
  
  .auth-buttons .main-header__btn {
    margin-right: 0;
  }
  
  .auth-buttons .eduhive-btn--border {
    margin-right: 5px;
  }
  
  /* Konum bilgisi için stil */
  .location-info {
    display: none;
  }
  
  .notification-dot {
    position: absolute;
    top: -5px;
    right: -5px;
    width: 12px;
    height: 12px;
    background-color: #ff3366;
    border-radius: 50%;
    border: 2px solid #fff;
    z-index: 101;
  }
  
  .badge {
    font-size: 0.75rem;
    font-weight: 600;
    padding: 0.2rem 0.5rem;
    margin-left: 5px;
  }
</style>

<!-- Dark Mode Script kaldırıldı -->